// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'plex_metadata.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

PlexMetadata _$PlexMetadataFromJson(Map<String, dynamic> json) => PlexMetadata(
  ratingKey: _readRatingKey(json, 'ratingKey') as String,
  key: json['key'] as String?,
  guid: json['guid'] as String?,
  studio: json['studio'] as String?,
  type: json['type'] as String?,
  title: json['title'] as String?,
  titleSort: json['titleSort'] as String?,
  contentRating: json['contentRating'] as String?,
  summary: json['summary'] as String?,
  rating: (json['rating'] as num?)?.toDouble(),
  audienceRating: (json['audienceRating'] as num?)?.toDouble(),
  userRating: (json['userRating'] as num?)?.toDouble(),
  year: (json['year'] as num?)?.toInt(),
  originallyAvailableAt: json['originallyAvailableAt'] as String?,
  thumb: json['thumb'] as String?,
  art: json['art'] as String?,
  duration: (json['duration'] as num?)?.toInt(),
  addedAt: (json['addedAt'] as num?)?.toInt(),
  updatedAt: (json['updatedAt'] as num?)?.toInt(),
  lastViewedAt: (json['lastViewedAt'] as num?)?.toInt(),
  grandparentTitle: json['grandparentTitle'] as String?,
  grandparentThumb: json['grandparentThumb'] as String?,
  grandparentArt: json['grandparentArt'] as String?,
  grandparentRatingKey: json['grandparentRatingKey'] as String?,
  parentTitle: json['parentTitle'] as String?,
  parentThumb: json['parentThumb'] as String?,
  parentRatingKey: json['parentRatingKey'] as String?,
  parentIndex: (json['parentIndex'] as num?)?.toInt(),
  index: (json['index'] as num?)?.toInt(),
  theme: json['theme'] as String?,
  grandparentTheme: json['grandparentTheme'] as String?,
  viewOffset: (json['viewOffset'] as num?)?.toInt(),
  viewCount: (json['viewCount'] as num?)?.toInt(),
  leafCount: (json['leafCount'] as num?)?.toInt(),
  viewedLeafCount: (json['viewedLeafCount'] as num?)?.toInt(),
  childCount: flexibleInt(json['childCount']),
  role: (json['Role'] as List<dynamic>?)?.map((e) => PlexRole.fromJson(e as Map<String, dynamic>)).toList(),
  mediaVersions: (json['Media'] as List<dynamic>?)
      ?.map((e) => PlexMediaVersion.fromJson(e as Map<String, dynamic>))
      .toList(),
  genre: _tagsFromJson(json['Genre'] as List?),
  director: _tagsFromJson(json['Director'] as List?),
  writer: _tagsFromJson(json['Writer'] as List?),
  producer: _tagsFromJson(json['Producer'] as List?),
  country: _tagsFromJson(json['Country'] as List?),
  collection: _tagsFromJson(json['Collection'] as List?),
  label: _tagsFromJson(json['Label'] as List?),
  style: _tagsFromJson(json['Style'] as List?),
  mood: _tagsFromJson(json['Mood'] as List?),
  audioLanguage: json['audioLanguage'] as String?,
  subtitleLanguage: json['subtitleLanguage'] as String?,
  subtitleMode: flexibleInt(json['subtitleMode']),
  playlistItemID: (json['playlistItemID'] as num?)?.toInt(),
  playQueueItemID: (json['playQueueItemID'] as num?)?.toInt(),
  librarySectionID: (json['librarySectionID'] as num?)?.toInt(),
  librarySectionTitle: json['librarySectionTitle'] as String?,
  ratingImage: json['ratingImage'] as String?,
  audienceRatingImage: json['audienceRatingImage'] as String?,
  tagline: json['tagline'] as String?,
  originalTitle: json['originalTitle'] as String?,
  editionTitle: json['editionTitle'] as String?,
  subtype: json['subtype'] as String?,
  extraType: (json['extraType'] as num?)?.toInt(),
  primaryExtraKey: json['primaryExtraKey'] as String?,
  clearLogo: json['clearLogo'] as String?,
  backgroundSquare: json['backgroundSquare'] as String?,
);

Map<String, dynamic> _$PlexMetadataToJson(PlexMetadata instance) => <String, dynamic>{
  'ratingKey': instance.ratingKey,
  'key': instance.key,
  'guid': instance.guid,
  'studio': instance.studio,
  'type': instance.type,
  'title': instance.title,
  'titleSort': instance.titleSort,
  'contentRating': instance.contentRating,
  'summary': instance.summary,
  'rating': instance.rating,
  'audienceRating': instance.audienceRating,
  'userRating': instance.userRating,
  'year': instance.year,
  'originallyAvailableAt': instance.originallyAvailableAt,
  'thumb': instance.thumb,
  'art': instance.art,
  'duration': instance.duration,
  'addedAt': instance.addedAt,
  'updatedAt': instance.updatedAt,
  'lastViewedAt': instance.lastViewedAt,
  'grandparentTitle': instance.grandparentTitle,
  'grandparentThumb': instance.grandparentThumb,
  'grandparentArt': instance.grandparentArt,
  'grandparentRatingKey': instance.grandparentRatingKey,
  'parentTitle': instance.parentTitle,
  'parentThumb': instance.parentThumb,
  'parentRatingKey': instance.parentRatingKey,
  'parentIndex': instance.parentIndex,
  'index': instance.index,
  'theme': instance.theme,
  'grandparentTheme': instance.grandparentTheme,
  'viewOffset': instance.viewOffset,
  'viewCount': instance.viewCount,
  'leafCount': instance.leafCount,
  'viewedLeafCount': instance.viewedLeafCount,
  'childCount': instance.childCount,
  'Role': instance.role,
  'audioLanguage': instance.audioLanguage,
  'subtitleLanguage': instance.subtitleLanguage,
  'subtitleMode': instance.subtitleMode,
  'playlistItemID': instance.playlistItemID,
  'playQueueItemID': instance.playQueueItemID,
  'librarySectionID': instance.librarySectionID,
  'librarySectionTitle': instance.librarySectionTitle,
  'ratingImage': instance.ratingImage,
  'audienceRatingImage': instance.audienceRatingImage,
  'tagline': instance.tagline,
  'originalTitle': instance.originalTitle,
  'editionTitle': instance.editionTitle,
  'subtype': instance.subtype,
  'extraType': instance.extraType,
  'primaryExtraKey': instance.primaryExtraKey,
  'clearLogo': instance.clearLogo,
  'backgroundSquare': instance.backgroundSquare,
};
