require 'dotenv/load'
Dotenv.load("../../.env")

default_platform(:ios)

platform :ios do
  desc "Build and deploy to App Store"
  lane :deploy_appstore do
    git_commit = `git rev-parse --short HEAD`.strip

    # Build the Flutter app
    sh("cd #{ENV['PWD']}/.. && flutter build ipa --dart-define=ENABLE_IN_APP_REVIEW=true --dart-define=ENABLE_SENTRY=true --dart-define=GIT_COMMIT=#{git_commit} --dart-define=SENTRY_ENVIRONMENT=app-store --split-debug-info=debug-info/ios")

    # Upload debug symbols
    sh("cd #{ENV['PWD']}/.. && ./scripts/upload-symbols.sh ios")

    # Upload to App Store
    upload_to_app_store(
      ipa: "../build/ios/ipa/Plezy.ipa",
      force: true,
      submit_for_review: false,
      skip_screenshots: true, # https://github.com/fastlane/fastlane/issues/29735
    )
  end
end
